apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: eribyteofficial/eribot
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: APP_ID
              valueFrom:
                secretKeyRef:
                  name: ${SECRET_NAME}
                  key: APP_ID
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: ${SECRET_NAME}
                  key: APP_SECRET
            - name: CRUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${SECRET_NAME}
                  key: CRUD_PASSWORD
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ${SECRET_NAME}
                  key: DISCORD_TOKEN
            - name: ENDPOINT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${SECRET_NAME}
                  key: ENDPOINT_PASSWORD
            - name: CRUD_OAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${SECRET_NAME}
                  key: CRUD_OAUTH_PASSWORD

            - name: CRUD_URL
              valueFrom:
                configMapKeyRef:
                  name: ${CONFIG_NAME}
                  key: CRUD_URL
            - name: ENCRYPT_URL
              valueFrom:
                configMapKeyRef:
                  name: ${CONFIG_NAME}
                  key: ENCRYPT_URL
                  
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  type: NodePort
  selector:
    app: ${APPLICATION_NAME}
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
